"""
PR reporter — generates structured output for CI consumption.

Formats:
- GitHub PR review comment (markdown)
- GitHub Actions annotations (::error, ::warning, ::notice)
- JSON summary for downstream tooling
- SARIF for GitHub Security tab integration
"""

import json
from typing import List, Dict, Any, Optional
from dataclasses import asdict


def generate_pr_comment(
    filepath: str,
    scanner_findings: List[Dict[str, Any]],
    ai_result: Dict[str, Any],
    test_summary: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate a GitHub PR review comment in markdown."""
    all_findings = scanner_findings + ai_result.get("findings", [])
    metrics = ai_result.get("metrics", {})
    verdict = ai_result.get("verdict", "request_changes")
    verdict_reason = ai_result.get("verdict_reason", "")

    sev_counts = metrics.get("by_severity", {})
    risk = metrics.get("risk_score", "?")

    # Verdict badge
    verdict_map = {
        "approve": ("✅", "Approved"),
        "request_changes": ("⚠️", "Changes Requested"),
        "block": ("🛑", "Blocked — Do Not Merge"),
    }
    badge_icon, badge_text = verdict_map.get(verdict, ("❓", "Unknown"))

    lines = []
    lines.append(f"## {badge_icon} CERBERUS: {badge_text}")
    lines.append("")
    lines.append(f"> **{filepath}** — Risk Score: **{risk}/10** — "
                 f"{metrics.get('total_issues', len(all_findings))} issues found")
    lines.append(f"> {verdict_reason}")
    lines.append("")

    # Severity summary
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["critical", "high", "medium", "low", "info"]:
        count = sev_counts.get(sev, 0)
        if count > 0:
            emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢", "info": "🔵"}
            lines.append(f"| {emoji.get(sev, '')} {sev.upper()} | {count} |")
    lines.append("")

    # Findings grouped by severity
    for sev in ["critical", "high", "medium", "low", "info"]:
        sev_findings = [f for f in all_findings if f.get("severity") == sev]
        if not sev_findings:
            continue
        lines.append(f"### {sev.upper()} findings")
        lines.append("")
        for f in sev_findings:
            fid = f.get("id", "?")
            title = f.get("title", "")
            loc = f.get("location", "")
            desc = f.get("description", "")
            rec = f.get("recommendation", "")
            cwe = f.get("cwe")
            cert = f.get("cert_c")

            lines.append(f"<details>")
            lines.append(f"<summary><code>{fid}</code> — {title} ({loc})</summary>")
            lines.append(f"")
            lines.append(f"{desc}")
            lines.append(f"")
            tags = []
            if cwe:
                tags.append(f"`{cwe}`")
            if cert:
                tags.append(f"`{cert}`")
            if tags:
                lines.append(f"References: {' '.join(tags)}")
                lines.append("")
            lines.append(f"**Fix:** {rec}")
            lines.append(f"</details>")
            lines.append("")

    # Unity test results
    if test_summary:
        lines.append("### 🧪 Unity Test Results")
        lines.append("")
        if test_summary.get("compile_error"):
            lines.append(f"⚠️ **Compilation failed:**")
            lines.append(f"```")
            lines.append(test_summary["compile_error"][:500])
            lines.append(f"```")
        else:
            total = test_summary.get("total", 0)
            passed = test_summary.get("passed", 0)
            failed = test_summary.get("failed", 0)
            ignored = test_summary.get("ignored", 0)
            lines.append(f"| Total | Passed | Failed | Ignored |")
            lines.append(f"|-------|--------|--------|---------|")
            lines.append(f"| {total} | ✅ {passed} | ❌ {failed} | ⏭️ {ignored} |")
            lines.append("")

            # List failures
            failures = [r for r in test_summary.get("results", []) if r.get("result") == "FAIL"]
            if failures:
                lines.append("**Failed tests:**")
                for f in failures:
                    lines.append(f"- `{f['test_name']}` — {f.get('message', 'assertion failed')}")
                lines.append("")

    lines.append("---")
    lines.append("*Generated by CERBERUS — deterministic scan + AI deep analysis + Unity regression tests*")

    return "\n".join(lines)


def generate_github_annotations(
    filepath: str,
    all_findings: List[Dict[str, Any]],
) -> str:
    """Generate GitHub Actions annotation commands."""
    lines = []
    sev_to_level = {
        "critical": "error",
        "high": "error",
        "medium": "warning",
        "low": "warning",
        "info": "notice",
    }
    for f in all_findings:
        level = sev_to_level.get(f.get("severity", "info"), "notice")
        line_num = f.get("line", 1)
        title = f.get("title", "Finding")
        fid = f.get("id", "")
        desc = f.get("description", "").replace("\n", " ")
        lines.append(f"::{level} file={filepath},line={line_num},title=[{fid}] {title}::{desc}")
    return "\n".join(lines)


def generate_json_summary(
    filepath: str,
    scanner_findings: List[Dict[str, Any]],
    ai_result: Dict[str, Any],
    test_summary: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate a JSON summary for downstream consumption."""
    return json.dumps({
        "file": filepath,
        "scanner_findings": scanner_findings,
        "ai_findings": ai_result.get("findings", []),
        "metrics": ai_result.get("metrics", {}),
        "summary": ai_result.get("summary", ""),
        "verdict": ai_result.get("verdict", "request_changes"),
        "verdict_reason": ai_result.get("verdict_reason", ""),
        "test_results": test_summary,
    }, indent=2)


def generate_sarif(
    filepath: str,
    all_findings: List[Dict[str, Any]],
) -> str:
    """Generate SARIF 2.1.0 for GitHub Security tab."""
    rules = []
    results = []
    rule_ids_seen = set()

    sev_to_sarif = {
        "critical": "error",
        "high": "error",
        "medium": "warning",
        "low": "note",
        "info": "note",
    }

    for f in all_findings:
        fid = f.get("id", "UNKNOWN")
        if fid not in rule_ids_seen:
            rule_ids_seen.add(fid)
            rules.append({
                "id": fid,
                "shortDescription": {"text": f.get("title", "")},
                "fullDescription": {"text": f.get("description", "")},
                "help": {"text": f.get("recommendation", "")},
                "properties": {
                    "tags": [f.get("category", "")],
                },
            })

        results.append({
            "ruleId": fid,
            "level": sev_to_sarif.get(f.get("severity", "info"), "note"),
            "message": {"text": f.get("description", "")},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": filepath},
                    "region": {"startLine": f.get("line", 1)},
                }
            }],
        })

    sarif = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "cerberus",
                    "version": "1.0.0",
                    "informationUri": "https://github.com/your-org/cerberus",
                    "rules": rules,
                }
            },
            "results": results,
        }],
    }

    return json.dumps(sarif, indent=2)
